[setup]
verbose = false
use_serial_display = true
use_ups_hat = true
auto_lldp_read = true
serial_display_type = "lcd_st7735"
serial_type = "spi"
serial_display_rotate = 0
serial_display_refresh_rate = 5
font_size = 14
show_chassis_id = true
show_name = true
show_management_ip = false
show_port_id = true
show_port_descr = false
show_auto_neg_current = true
show_auto_supported = true
show_auto_enabled = false
show_available_modes_str = true
show_vlan_id = true
show_power_supported = false
show_power_enabled = true
show_device_type = true
show_capability = false
