[setup]
verbose = false
use_serial_display = true
use_ups_hat = true
auto_lldp_read = true
serial_display_type = "lcd_st7735"
serial_type = "spi"
serial_display_rotate = 0
serial_display_refresh_rate = 5
serial_display_width = 128
serial_display_height = 128
serial_display_horizontal_offset = 1
serial_display_vertical_offset = 2
serial_display_background = true
font_size = 15
show_chassis_id = true
show_chassis_description = true
show_port_id = true
show_port_descr = true
show_auto_neg_current = true
show_auto_supported = true
show_auto_enabled = true
show_available_modes_str = true
show_vlan_id = true
show_power_supported = true
show_power_enabled = true
show_device_type = true

